filter:
    paths: ["src/*"]
build:
    environment:
        php:
            version: 8.1
    nodes:
        coverage:
            tests:
                override:
                    - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=tests/clover.xml
                      coverage:
                          file: tests/clover.xml
                          format: clover
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
tools:
    external_code_coverage: false
